  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/action?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: a1151342179
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
      show-sql:
        true
  server:
    port: 8084
